name: Minimal Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: dill-lk
          template: classic
          base: header, metadata
          config_timezone: Asia/Colombo
          filename: github-metrics.svg
          
          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Inject Outfit Font via CSS
          extras_css: |
            @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@400;700&display=swap');
            * { 
              font-family: 'Outfit', sans-serif !important; 
            }
